//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NackademinUppgift05
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalParent
    {
        public int ChildId { get; set; }
        public int ParentId { get; set; }
    
        public virtual Animal Child { get; set; }
        public virtual Animal Parent { get; set; }
    }
}
