//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NackademinUppgift05
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int AnimalId { get; set; }
        public int VeterinarianId { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Veterinarian Veterinarian { get; set; }
    }
}
