//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NackademinUppgift05
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZoophobiaContainer : DbContext
    {
        public ZoophobiaContainer()
            : base("name=ZoophobiaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<Veterinarian> Veterinarians { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<EaterType> EaterTypes { get; set; }
        public virtual DbSet<Environment> Environments { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<AnimalParent> AnimalParents { get; set; }
    }
}
